In [6]:
import sys
sys.path.append("../src")

import pandas as pd

from content_based import (
    build_content_based_model,
    recommend_movies
)

In [ ]:
movies = pd.read_csv("../data/raw/movies.csv")
tags = pd.read_csv("../data/raw/tags.csv")
ratings = pd.read_csv("../data/raw/ratings.csv")

In [ ]:
artifacts = build_content_based_model(
    movies=movies,
    tags=tags,
    ratings=ratings,
    weight_genres=0.4,
    weight_tags=0.6,
    popularity_percentile=0.70
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/305 [00:00<?, ?it/s]

In [ ]:
movies_model = artifacts["movies_model"]
similarity_content = artifacts["similarity_content"]

In [9]:
recommend_movies(
    title="Godfather: Part III, The (1990)",
    movies_model=movies_model,
    similarity_content=similarity_content,
    top_n=10,
    quality_weight=0.2
)

,movieId,title,genres,decade,similarity_content,quality_score,final_score,v,R
0,431,Carlito's Way (1993),Crime|Drama,1990s_decade,0.774931,0.692706,0.758486,42.0,3.738095
1,1221,"Godfather: Part II, The (1974)",Crime|Drama,1970s_decade,0.660378,0.917880,0.711879,129.0,4.259690
2,1213,Goodfellas (1990),Crime|Drama,1990s_decade,0.624802,0.913493,0.682540,126.0,4.250000
3,16,Casino (1995),Crime|Drama,1990s_decade,0.624802,0.775158,0.654873,82.0,3.926829
4,1245,Miller's Crossing (1990),Crime|Drama|Film-Noir|Thriller,1990s_decade,0.607082,0.837979,0.653261,20.0,4.225000
5,1466,Donnie Brasco (1997),Crime|Drama,1990s_decade,0.624802,0.696084,0.639058,52.0,3.740385
6,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1990s_decade,0.557589,0.900827,0.626237,307.0,4.197068
7,1089,Reservoir Dogs (1992),Crime|Mystery|Thriller,1990s_decade,0.546624,0.894366,0.616173,131.0,4.202290
8,4262,Scarface (1983),Action|Crime|Drama,1980s_decade,0.570307,0.774573,0.611160,67.0,3.932836
9,858,"Godfather, The (1972)",Crime|Drama,1970s_decade,0.521522,0.935625,0.604343,192.0,4.289062

In [10]:
recommend_movies(
    title="Godfather: Part III, The (1990)",
    movies_model=movies_model,
    similarity_content=similarity_content,
    top_n=10,
    quality_weight=0.4
)

,movieId,title,genres,decade,similarity_content,quality_score,final_score,v,R
0,1221,"Godfather: Part II, The (1974)",Crime|Drama,1970s_decade,0.660378,0.917880,0.763379,129.0,4.259690
1,431,Carlito's Way (1993),Crime|Drama,1990s_decade,0.774931,0.692706,0.742041,42.0,3.738095
2,1213,Goodfellas (1990),Crime|Drama,1990s_decade,0.624802,0.913493,0.740278,126.0,4.250000
3,1245,Miller's Crossing (1990),Crime|Drama|Film-Noir|Thriller,1990s_decade,0.607082,0.837979,0.699441,20.0,4.225000
4,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1990s_decade,0.557589,0.900827,0.694885,307.0,4.197068
5,858,"Godfather, The (1972)",Crime|Drama,1970s_decade,0.521522,0.935625,0.687163,192.0,4.289062
6,1089,Reservoir Dogs (1992),Crime|Mystery|Thriller,1990s_decade,0.546624,0.894366,0.685721,131.0,4.202290
7,16,Casino (1995),Crime|Drama,1990s_decade,0.624802,0.775158,0.684944,82.0,3.926829
8,2959,Fight Club (1999),Action|Crime|Drama|Thriller,1990s_decade,0.498035,0.930207,0.670904,218.0,4.272936
9,318,"Shawshank Redemption, The (1994)",Crime|Drama,1990s_decade,0.437591,1.000000,0.662555,317.0,4.429022